### ISSUE TITLE
[featurerequest] cross-platform support?!

### ISSUE THREAD

**Issue by s-light** [jnweiger/led-badge-44x11#2]
idea: would be nice to have a easy way (for a normal end-user) to install this cross-platform.

this is a collection of things i found during my search & how it could work - 
all untested yet...

## libusb

currently the script uses libusb to access the HID-Device. 
its easy to install for linux but a little bit harder for Mac OS or windows:
(as fare as i found - please proof me wrong?! ;-) )
- Linux (Ubuntu or other debian based...)
simple as `sudo apt install python3-usb` (as written in the current instructions)
this installs [libusb](https://libusb.info/) and [pyusb](https://pypi.org/project/pyusb/) (info from [package description](https://packages.debian.org/stretch/python3-usb))
- macOS
according to [this answer](https://stackoverflow.com/a/45885232/574981) libusb should be working with [Homebrew](https://brew.sh/)
`brew install libusb`
additionally we need pyusb: `pip3 install pyusb`
- Windows
there is a [libusb Windows WikiPage](https://github.com/libusb/libusb/wiki/Windows) that tells us that there are [Binary Snapshots](https://github.com/libusb/libusb/wiki/Windows#binary-snapshots) as 7zip in the [releases](https://github.com/libusb/libusb/releases/latest)
but these just containing the dlls - no installer:
![image](https://user-images.githubusercontent.com/1340319/57160431-10e8a380-6de9-11e9-8339-17a2e0183606.png)
so we need to copy theme to the correct location so the 
pyusb lib can find them?! (i have no clue :see_no_evil: )

there is [libusb](https://pypi.org/project/libusb/) at pypi ([github](https://github.com/karpierz/libusb)) that states:

> Requirements
> It is fully independent package.
> All necessary things are installed during the normal installation process.
> ATTENTION: currently works and tested only for Windows.

and yes- if you look at the source it [includes the dll](https://github.com/karpierz/libusb/tree/master/src/libusb/_platform/_windows/x64).
but as mentioned - only for windows :crying_cat_face: 

## other option: switch library ?

the [libusb FAQ](https://github.com/libusb/libusb/wiki/FAQ#does-libusb-support-usb-hid-devices) also recommends the [HIDAPI library](https://github.com/signal11/hidapi) for HID things.
but it seems this lib is a bit [in a unmaintained state](https://github.com/signal11/hidapi/issues/373) currently..
on my search i found [cython-hidapi](https://github.com/trezor/cython-hidapi) as a python API for this. (called [hidapi](https://pypi.org/project/hidapi/) at pypi)
→ this would mean Cython as dependency..
i also found [pyhidapi](https://github.com/apmorton/pyhidapi) (named [hid](https://pypi.org/project/hid/#description) in pypi)
but installation in osx seems trouble some too...

## result
there is no easy to install solution already out there?

hope someone else has better news on this ;-)

**Comment by jnweiger** [comment]
Thanks for the research. Please compare with https://github.com/jnweiger/inkscape-silhouette/blob/master/silhouette/Graphtec.py#L30

**Comment by s-light** [comment]
this comment is just a list / overview of the different *python hid packages* i found during research:

| pypi | source | apt |
| -- | -- | -- |
| [hid](https://pypi.org/project/hid/) | [pyhidapi](https://github.com/apmorton/pyhidapi) | ? []() |
| [hidapi](https://pypi.org/project/hidapi/) | [cython-hidapi](https://github.com/trezor/cython-hidapi) | [python-hid](https://packages.debian.org/stretch/python-hid) |
| [hidapi-cffi](https://pypi.org/project/hidapi-cffi/) | [hidapi-cffi](https://github.com/jbaiter/hidapi-cffi) | [python-hidapi](https://packages.debian.org/stretch/python-hidapi) |
| [pyhidapi](https://pypi.org/project/pyhidapi/) | [pyhidapi](https://gitlab.com/NF6X_Archive/pyhidapi) | ? []() |

**Comment by jnweiger** [comment]
For windows there is also pywinusb, which can be used like this:
```
#
#    (install python from python.org)
#      [x] install Launcher for all Users
#      [x] Add Python 3.7 to PATH
#    pip install pywinusb
#
import pywinusb.hid as hid
filter = hid.HidDeviceFilter(vendor_id=0x0416, product_id=0x5020)
dev = filter.get_devices()[0]
print(dev)
dev.open()
report = dev.find_output_reports()[0]
print(report)
buffer= [0x00]*65
buffer[0]=0x0
buffer[1]=0x01
buffer[2]=0x00
buffer[3]=0x01
report.send(buffer)
dev.close()
```

But the send buffer must be exactly 65 bytes. Probably not raw enough for us.

**Comment by s-light** [comment]
for a windows and a 'raw' usb version (no special hid library) we could try a ifelse handling with
[libusb](https://pypi.org/project/libusb/) [(source)](https://github.com/karpierz/libusb)
it should install all needed things for windows with `pip install libusb`

**Comment by jnweiger** [comment]
pywinusb has a report.set_raw_data() method, but that is still not sufficiently raw. wireshark shows only some parts of my message getting through, with other data intermixed. Not suitable for us.

**Comment by s-light** [comment]
### memo :memo: 
if packaging is consider: [have a look at this stackoverflow question](https://stackoverflow.com/questions/12059509/create-a-single-executable-from-a-python-project) for some options..
likely gets complicated with this hole librarie things...

**Comment by jnweiger** [comment]
https://github.com/jnweiger/led-badge-44x11/commit/c47bc9a03a34f5f15705bbf9c90036bf056b82b0
should fix windows10 support. 

@AnnabelleLee1987 install procedures on on Ubuntu, Mac, Windows are now all described in the README. None of them are trivial, sorry. Please test if that gets you going. Thanks!

**Comment by jnweiger** [comment]
Should we close here, or keep this open for reference?

**Comment by s-light** [comment]
i think we can close this - as the original request is - at least partly - solved.

---
just some closing thoughts:
currently i think we know that the only way to streamline all this is :
- get [libusb](https://pypi.org/project/libusb/) from [this repository](https://github.com/karpierz/libusb) to include and work cross platform... 
- or write a wrapper similar to libusb but based on the available *hid libs*...

→ but i don't know if one of this is in any way easy possible..

**Comment by jnweiger** [comment]
inf-wizard seems to explode under windows 7, without installing any drivers.
 
1) Start als "admin"
2) <Next>
3) Choose the entry with "0x0416 0x5020 LS32 Custm HID" + <Next>
4) Confirm where it says "Vendor ID=0x12AB"
<Next>
5) <Save>
6)  "Unknown Error: 1" :-(
... now the only choice is
7) <Cancel>
