### ISSUE TITLE
Suggest udev rule except for sudo

### ISSUE THREAD

**Issue by AnnabelleLee1987** [jnweiger/led-badge-44x11#5]
e.g.:

SUBSYSTEM=="usb", ATTR{idVendor}=="0fcf", ATTR{idProduct}=="1008", MODE="666"

**Comment by jnweiger** [comment]
Thanks for the idea. Added a rules file that works with the usb.core module. 
But I cannot find a combination that works with pyhidapi. If there is one, please reopen.
