### ISSUE TITLE
Space problems with Python 2.7

### ISSUE THREAD

**Issue by semaf** [jnweiger/led-badge-44x11#9]
Hey,

Just want to inform you that the output of the text "Hello World" is "Hello**ä**World".

**Comment by jnweiger** [comment]
Thanks for the report, it works correctly for me with python-3.6.7 both pyhidapi and usb.core
Do you have more details? Linux system, python version, installed pyhidapi or usb.core modules?

**Comment by semaf** [comment]
Yes.

Python 2.7
pyhidapi (0.0.2)
pyusb (1.0.0)

Installed is python-usb (1.0.0-1)

**Comment by jnweiger** [comment]
pyhidapi sees not so relible. I added a patch today to make it better. You may also want to try to disable loading of pyhidapi. Either by uninstalling or by misspelling it in the script, then it will fall back to usb.core.

I wonder why python 2.7 works for you at all. I believe one of the latest patches killed the compatibility. This also needs fixing.

**Comment by semaf** [comment]
Tested without pyhidapi or usb.core has same result. Installed Python 3.6 solved it.

**Comment by jnweiger** [comment]
Using pyhidapi with python-2.7 explodes for me like this:
```
Traceback (most recent call last):
  File "led-badge-11x44.py", line 466, in <module>
    pyhidapi.hid_write(dev, buf)
  File "/usr/local/lib/python2.7/dist-packages/pyhidapi/pyhidapi.py", line 638, in hid_write
    buf[n] = data[n]
TypeError: one character string expected
```
Where data[n] is a plain integer, oh well, it wants a char. that is bad.
Workaround: with pyhton-2.7 we always use usb.core

**Comment by jnweiger** [comment]
the original issue was caused by python-2.7 interpreting our charmap as ascii-bytes. We have to prefix the strings here with u"" to make them python-2.7 compatible.
